### ISSUE TITLE
URL Jumper

### ISSUE THREAD

**Issue by M4SK3D** [M4SK3D/State-Results-Project#3]
URL adds random number, maybe due to incorrect parsing, Check this over large ranges

**Comment by purushothaman-p** [comment]
Tested with test cases ranging from 836000-836050 and 838000-838050. Successful url parsing.

**Comment by M4SK3D** [comment]
Solution patched. Involved re-tasking the `keyboard.write(url)` to `shell.SendKeys(url)`
