### ISSUE TITLE
Random URL invoked

### ISSUE THREAD

**Issue by purushothaman-p** [M4SK3D/State-Results-Project#5]
When the time given by the user is smaller than what it is expected, the code jumps to the any random URL . In this case it was google images website and nic home page. This issue can be temporarily faced by increasing the time delays.

**Comment by M4SK3D** [comment]
Is the jump all random?

**Comment by purushothaman-p** [comment]
Not completely random, but it jumps to the URL which the user had viewed long ago as google chrome suggests URL names while typing. Another issue when the time being reduced is that the data is typed and instead of clicking "Get Marks" it skips it and clicks "Clear". So it removes the data which was typed earlier

**Comment by M4SK3D** [comment]
So maybe with enough test cases we may be able to identify ideal minimum time limit......we shall cap it at that

**Comment by M4SK3D** [comment]
Identified the cause of the bug as a fault with mistimed SendKeys() routine. Keys were being sent at the wrong time. Could have been due to user intervention (something so trivial as moving the pointer) or due to mistiming the Next Result delay.
